package ar.com.cristal.creditos.common;

public enum EstadoCreditoEnum {
	PENDIENTE_DEPOSITO, ACTIVO, CANCELADO, ADEUDADO, REFINANCIADO, LEGALES, FINANCIADO, 
	CANCELADO_BAJA, CANCELADO_EJECUCION, ANULADO, PENDIENTE_CHEQUE, PENDIENTE_EFECTIVO
}
